# k8s/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: goland-app-service
spec:
  type: NodePort
  selector:
    app: goland-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31567

